---
- name: Install Node.js, npm, Gatsby CLI, gcc-c++, and make
  hosts: instances # Le nom du groupe d'hôtes spécifié dans le fichier hosts.ini
  become: yes # Privilège sudo
  tasks:
    - name: Install gcc-c++ and make
      yum:
        name:
          - gcc-c++
          - make
        state: present

    - name: Install Node.js and npm from official repository
      yum:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Gatsby CLI with npm
      npm:
        name: gatsby-cli
        global: yes

    - name: Install the EPEL repository package
      yum:
        name: epel-release
        state: present
